### ISSUE TITLE
The info when entered on student registration closes the server

### ISSUE THREAD

**Issue by Vedaant-Rajoo** [shivam-kapila/EntryToHack3.0#14]
the error seen is

**TypeError: Cannot read property 'members' of null
    at /home/newedia/Desktop/EntryToHack3.0/routes/student.js:53:58
    at /home/newedia/Desktop/EntryToHack3.0/node_modules/mongoose/lib/model.js:4669:16
    at /home/newedia/Desktop/EntryToHack3.0/node_modules/mongoose/lib/query.js:4090:12
    at model.Query.Query._completeOne (/home/newedia/Desktop/EntryToHack3.0/node_modules/mongoose/lib/query.js:1934:12)
    at Immediate.Query.base.findOne.call (/home/newedia/Desktop/EntryToHack3.0/node_modules/mongoose/lib/query.js:1994:10)
    at Immediate._onImmediate (/home/newedia/Desktop/EntryToHack3.0/node_modules/mquery/lib/utils.js:116:16)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)**

**Comment by shivam-kapila** [comment]
I will see to it. Please comment the route link here
